name: Docker Build and Deploy

on:
  push:
    branches:
      - main # Jalankan workflow ketika ada push ke branch `main`

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout kode dari repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # 2. Setup Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # 3. Login ke DockerHub (opsional, jika ingin push image)
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # 4. Build Docker Image
    - name: Build Docker Image
      run: |
        docker build -t alhusnaahanifah/hostingproject:newest 
