name: Docker Build and Deploy

on:
  push:
    branches:
      - main # Jalankan workflow ketika ada push ke branch `main`

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout kode dari repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # 2. Setup Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # 3. Login ke DockerHub
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # 4. Build and Push Docker Image
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: alhusnaahanifah/hostingproject:newest

    # 5. Jalankan container untuk testing
    - name: Run Docker Container for Testing
      run: |
        docker run -d -p 8080:80 --name test-container alhusnaahanifah/hostingproject:newest
        sleep 5 # Tunggu sebentar agar container sepenuhnya berjalan
        docker ps # Verifikasi container berjalan
        curl -f http://localhost:8080 || (echo "Test failed!" && exit 1)

    # 6. Hentikan dan hapus container setelah testing
    - name: Cleanup
      if: always()
      run: |
        docker stop test-container || true
        docker rm test-container || true
